### ISSUE TITLE
 DOCUMENTATION

### ISSUE THREAD

**Issue by HILMIONELL97** [HILMIONELL97/INTEGRATION-WEB.github.io#1]
- [x] BEM

- [x] NODE ( NPM & SASS)

- [x] IINSTALLATION DE L'ENVIRONNEMENT DU TRAVAIL

**Comment by youssefbm** [comment]
jetez un coup d'oeil sur cette vidéo

**Comment by HILMIONELL97** [comment]
Voila , je fini la partie du documentation et je passe à la partie DEV.

**Comment by youssefbm** [comment]
N'OUBLIER PAS D'APPLIQUER LE BEM SASS ET METTRE À JOUR VOTRE REPO
